server:
  port: 8762

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/happygluck/springbootSample/        # \u914D\u7F6Egit\u4ED3\u5E93\u7684\u5730\u5740
          search-paths: keyijie                                      # git\u4ED3\u5E93\u5730\u5740\u4E0B\u7684\u76F8\u5BF9\u5730\u5740\uFF0C\u53EF\u4EE5\u914D\u7F6E\u591A\u4E2A\uFF0C\u7528,\u5206\u5272\u3002
          username: happygluck                                        # git\u4ED3\u5E93\u7684\u8D26\u53F7
          password: yjhIdtf0                                         # git\u4ED3\u5E93\u7684\u5BC6\u7801

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/