server:
  port: 8081

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/happygluck/config.git
          search-paths: keyijie
          default-label: master
          #username: happygluck
          #password: 1111111111

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/